name: ci

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '15 3 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: imrehg/archlinux-makepkg:latest
          cache-from: type=registry,ref=imrehg/archlinux-makepkg:latest
          cache-to: type=inline